#!/bin/bash

set -eo pipefail

DEPLOYMENT=`echo $HOSTNAME | sed -e 's/^\(.*\)-[^-]*-[^-]*$/\1/'`
NAMESPACE=`cat /var/run/secrets/kubernetes.io/serviceaccount/namespace`

# Start the Jupyter notebook instance.
. /opt/app-root/bin/start-notebook.sh
